### ISSUE TITLE
Needs 'on' events for common UI ops

### ISSUE THREAD

**Issue by avoidwork** [avoidwork/haro#45]
Need a hook for the following:

- [ ] batch
- [ ] clear
- [ ] delete
- [ ] error
- [ ] set
- [ ] sync

**Comment by collinglass** [comment]
setUri would be nice too

**Comment by avoidwork** [comment]
wouldn't that be sync?

**Comment by avoidwork** [comment]
yeah, it's covered with sync, which is what it's calling :+1:

**Comment by collinglass** [comment]
perfect

**Comment by avoidwork** [comment]
Just to be clear, some of these become a sequence:

sync: clear > batch > set
batch: (set || delete)* n

I would recommend debouncing your event listeners if using 'batch', 'set' or 'delete'.
